# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
# - master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: Validate
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'validate'
        allowTelemetryCollection: true
  - job: Plan
    steps:
    - task: TerraformCLI@0
      enabled: false
      inputs:
        command: 'plan'
        environmentServiceName: 'Azure subscription 1(5198ab11-bed1-4a17-9205-df35c05f87b9)'
        allowTelemetryCollection: true