trigger: none

pool:
  vmImage: ubuntu-latest
stages:
  - stage: DL
    jobs:
    - job: DL_moonjun
      steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'specific'
          project: '9a591d1a-b59e-4089-a839-aaf3cf17a3a9'
          pipeline: '152'
          buildVersionToDownload: 'specific'
          buildId: '6556'
          downloadType: 'single'
          artifactName: 'tf_state'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: TerraformCLI@0
        inputs:
          command: 'init'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        inputs:
          command: 'destroy'
          environmentServiceName: 'Azure subscription 1(9fde5dd2-3d1a-4575-80c2-9ca0b55f5fc0)'
          allowTelemetryCollection: true
    - job: DL_revature
      steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'specific'
          project: '9a591d1a-b59e-4089-a839-aaf3cf17a3a9'
          pipeline: '152'
          buildVersionToDownload: 'specific'
          buildId: '6182'
          downloadType: 'single'
          artifactName: 'tf_state'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: TerraformCLI@0
        inputs:
          command: 'destroy'
          environmentServiceName: 'RevatureProject3ARMSubscription'
          allowTelemetryCollection: true
