trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DL
    jobs:
    - job: DL
      steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'specific'
          project: '9a591d1a-b59e-4089-a839-aaf3cf17a3a9'
          pipeline: '152'
          buildVersionToDownload: 'specific'
          buildId: '6182'
          downloadType: 'single'
          artifactName: 'tf_state'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: TerraformCLI@0
        inputs:
          command: 'destroy'
          environmentServiceName: 'RevatureProject3ARMSubscription'
          allowTelemetryCollection: true
