pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: init
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        allowTelemetryCollection: true

    - task: TerraformCLI@0
      enabled: false
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        allowTelemetryCollection: true

    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceName: 'Azure subscription 1(9fde5dd2-3d1a-4575-80c2-9ca0b55f5fc0)'
        allowTelemetryCollection: true

    - task: TerraformCLI@0
      enabled: false
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceName: 'Azure subscription 1(9fde5dd2-3d1a-4575-80c2-9ca0b55f5fc0)'
        allowTelemetryCollection: true

    - script: "terraform output kube_config_dev >> may24_devops_config_dev"
    
    - script: "ls $(System.DefaultWorkingDirectory)"
    - script: "ls $(System.DefaultWorkingDirectory)/terraform"
    - script: "ls $(Pipeline.Workspace)"
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/terraform'
        artifact: 'may24_devops_config_dev'
        publishLocation: 'pipeline'
