pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: validate
    steps:
    - script: "ls"
    - task: TerraformCLI@0
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory/terraform'
        allowTelemetryCollection: true
  - job: init
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        allowTelemetryCollection: true
  - job: plan
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceName: 'Azure subscription 1(5198ab11-bed1-4a17-9205-df35c05f87b9)'
        allowTelemetryCollection: true