trigger: none

pool:
  vmImage: ubuntu-latest


stages:
- stage:
  jobs:
  - job:
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'RevatureProject3ARMSubscription-project3-common'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az account show > output.txt'
        addSpnToEnvironment: true
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/output.txt'
        artifact: 'output'
        publishLocation: 'pipeline'