trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  terraformDirectory: $(System.DefaultWorkingDirectory)/terraform
  branch: master
  # may24_devops_subsription: 'Azure subscription 1(5198ab11-bed1-4a17-9205-df35c05f87b9)'
  may24_devops_subscription: 'Azure subscription 1(9fde5dd2-3d1a-4575-80c2-9ca0b55f5fc0)'

stages:
- stage: Terraform
  jobs:
  - job: init
    steps:
    - script: 'echo $(terraformDirectory) + $(branch)'
    - template: azure-templates/dl-tfstate-template.yaml
      parameters:
        branchName: $(branch)
        directory: $(terraformDirectory)

    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: 'terraform'
        allowTelemetryCollection: true
      displayName: "init"

    - task: TerraformCLI@0
      enabled: true
      inputs:
        command: 'validate'
        workingDirectory: 'terraform'
        allowTelemetryCollection: true
      displayName: "Validate"

    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: 'terraform'
        environmentServiceName: $(may24_devops_subscription)
        allowTelemetryCollection: true
      displayName: "Plan"

    - task: TerraformCLI@0
      enabled: 'true'
      inputs:
        command: 'apply'
        workingDirectory: 'terraform'
        environmentServiceName: $(may24_devops_subscription)
        allowTelemetryCollection: true
      displayName: "Apply"

    # Output kubeconfig details into file
    - script: "terraform output kube_config_dev >> may24_devops_config_dev"
      workingDirectory: 'terraform'

    - script: "terraform output kube_config_staging >> may24_devops_config_staging"
      workingDirectory: 'terraform'

    # Delete EOD output from first and last lines of dev/staging config file
    - script: "sed -i '1d;$d' may24_devops_config_dev"
      workingDirectory: 'terraform'

    - script: "sed -i '1d;$d' may24_devops_config_staging"
      workingDirectory: 'terraform'

    # Publish the kubeconfig files as artifacts
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'terraform/may24_devops_config_dev'
        artifact: 'kubeconfig_dev'
        publishLocation: 'pipeline'
      displayName: Publish dev kubeconfig

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'terraform/may24_devops_config_staging'
        artifact: 'kubeconfig_staging'
        publishLocation: 'pipeline'
      displayName: Publish staging kubeconfig

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'terraform/terraform.tfstate'
        artifact: 'tf_state'
        publishLocation: 'pipeline'
      displayName: Publish state file