trigger: none

pool:
  vmImage: ubuntu-latest


stages:
- stage:
  jobs:
  - job:
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'RevatureProject3ARMSubscription-project3-common'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az account show'
        addSpnToEnvironment: true