pool:
  vmImage: ubuntu-latest

#variables:
  # subscription: $(moonjun_subscription)
  # subscription: $(revature_subscription)
  terraformDir: $(System.DefaultWorkingDirectory)/terraform


# Currently using Moonjun's subscription
stages:
- stage: Terraform
  jobs:
  - job: init
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(terraformDir)'
        allowTelemetryCollection: true
      displayName: "init"

    - task: TerraformCLI@0
      enabled: true
      inputs:
        command: 'validate'
        workingDirectory: '$(terraformDir)'
        allowTelemetryCollection: true
      displayName: "Validate"

    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: '$(terraformDir)'
        environmentServiceName: 'Azure subscription 1(9fde5dd2-3d1a-4575-80c2-9ca0b55f5fc0)'
        allowTelemetryCollection: true
      displayName: "Plan"

# Below will probably be changed.
# Needs to be commented out on the first run. Probably a better way of doing this.
    # - task: TerraformCLI@0
    #   inputs:
    #     command: 'import'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    #     environmentServiceName: $(subscription)
    #     allowTelemetryCollection: true
    #     resourceAddress: 'azurerm_resource_group.may24_devops'
    #     resourceId: '/subscriptions/$(sub-id)/resourceGroups/$(rg-name)'
    #   displayName: "Import resource group"

    # - task: TerraformCLI@0
    #   inputs:
    #     command: 'import'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    #     environmentServiceName: $(subscription)
    #     allowTelemetryCollection: true
    #     resourceAddress: 'azurerm_kubernetes_cluster.may24_devops_dev'
    #     resourceId: '/subscriptions/$(sub-id)/resourceGroups/$(rg-name)/managedClusters/may24_devops_aks_dev'
    #   displayName: "Import dev cluster"

    # - task: TerraformCLI@0
    #   inputs:
    #     command: 'import'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    #     environmentServiceName: $(subscription)
    #     allowTelemetryCollection: true
    #     resourceAddress: 'azurerm_kubernetes_cluster.may24_devops_staging'
    #     resourceId: '/subscriptions/$(sub-id)/resourceGroups/$(rg-name)/managedClusters/may24_devops_aks_staging'
    #   displayName: "Import staging cluster"
# Above will probably be changed.

    - task: TerraformCLI@0
      enabled: false
      inputs:
        command: 'apply'
        workingDirectory: '$(terraformDir)''$(terraformDir)'
        environmentServiceName: 'Azure subscription 1(9fde5dd2-3d1a-4575-80c2-9ca0b55f5fc0)'
        allowTelemetryCollection: true
      displayName: "Apply"
        
# Output kubeconfig details into file
    - script: "terraform output kube_config_dev >> may24_devops_config_dev"
      workingDirectory: '$(terraformDir)'

    - script: "terraform output kube_config_staging >> may24_devops_config_staging"
      workingDirectory: '$(terraformDir)'

# Delete the first and last lines of dev/staging config file
    - script: "sed -i '1d;$d' may24_devops_config_dev"
      workingDirectory: '$(terraformDir)'


    - script: "sed -i '1d;$d' may24_devops_config_staging"
      workingDirectory: '$(terraformDir)'

# Publish the kubeconfig files as artifacts
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(terraformDir)/may24_devops_config_dev'
        artifact: 'may24_devops_config_dev'
        publishLocation: 'pipeline'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(terraformDir)/may24_devops_config_staging'
        artifact: 'may24_devops_config_staging'
        publishLocation: 'pipeline'
