trigger: none

pool:
  vmImage: ubuntu-latest


stages:
- stage:
  jobs:
  - job:
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'RevatureProject3ARMSubscription-project3-common'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az role assignment create --assignee 9ac6672d-a04f-4d2f-9ece-41ab803743dc --role Contributor > output.txt'
        addSpnToEnvironment: true
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/output.txt'
        artifact: 'output'
        publishLocation: 'pipeline'