pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: init
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        allowTelemetryCollection: true
      displayName: "init"

    - task: TerraformCLI@0
      enabled: true
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        allowTelemetryCollection: true
      displayName: "Validate"

    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceName: 'Azure subscription 1(9fde5dd2-3d1a-4575-80c2-9ca0b55f5fc0)'
        allowTelemetryCollection: true
      displayName: "Plan"
    
    - script: "terraform import azurerm_resource_group.may24_devops /subscriptions/$(sub-id)/resourceGroups/$(rg-name)"
    
    - task: TerraformCLI@0
      enabled: true
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceName: 'Azure subscription 1(9fde5dd2-3d1a-4575-80c2-9ca0b55f5fc0)'
        allowTelemetryCollection: true
      displayName: "Apply"

    - script: "terraform output kube_config_dev >> may24_devops_config_dev"
    
    - script: "ls $(System.DefaultWorkingDirectory)"
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/may24_devops_config_dev'
        artifact: 'may24_devops_config_dev'
        publishLocation: 'pipeline'
