trigger: none

pool:
  vmImage: ubuntu-latest


stages:
- stage:
  jobs:
  - job:
    steps:
    - task: AzureCLI@1
      enabled: false
      inputs:
        azureSubscription: 'RevatureProject3ARMSubscription-project3-common'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create \
            --name storage-resource-group \
            --location westus
    - task: AzureCLI@1
      enabled: false
      inputs:
        azureSubscription: 'RevatureProject3ARMSubscription-project3-common'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage account create \
            --name storagep3 \
            --resource-group storage-resource-group \
            --location westus \
            --sku Standard_RAGRS \
            --kind StorageV2
    
    - task: AzureCLI@1
      inputs:
        azureSubscription: 'RevatureProject3ARMSubscription-project3-common'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage container create \
              --account-name storagep3 \
              --name tf-state-file-container \
              --auth-mode login